---
- name: Include variables.
  include_vars: "debian.yml"

- name: apply iptables monitoring rules
  template:
    src: iptables-monitoring.j2
    dest: /etc/iptables-custom/iptables-monitoring
    owner: root
    group: root
    mode: 0644
  notify: restart iptables-custom service

- name: Ensure munin-node is installed (Debian).
  apt:
    name: munin-node
    state: present

- name: Copy munin-node configuration.
  template:
    src: munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
    owner: root
    group: root
    mode: 0644
  notify: restart munin-node

- name: Generate plugin configuration.
  template:
    src: plugin-conf.j2
    dest: /etc/munin/plugin-conf.d/ansible.conf
    owner: root
    group: root
    mode: 0644
  notify: restart munin-node

- name: Enable additional plugins.
  file:
    path: "{{ munin_plugin_dest_path }}{{ item.name }}"
    src: "{{ munin_plugin_src_path }}{{ item.plugin | default( item.name ) }}"
    state: link
  with_items: "{{ munin_node_plugins }}"
  notify: restart munin-node

- name: Ensure munin-node is running.
  service:
    name: munin-node
    state: started
    enabled: yes
